// local imports
import shippingIcon from "./assets/free-shiping-icon.svg";
import paymentIcon from "./assets/quick-payment-icon.svg";
import supportIcon from "./assets/support-icon.svg";
import productOneIcon from "./assets/product-one.svg";
import productTwoIcon from "./assets/produc-two.svg";
import productThreeIcon from "./assets/product-three.svg";
import plantIcon from "./assets/plant-icon.svg";
import sunIcon from "./assets/sun-icon.svg";
import waterIcon from "./assets/water-icon.svg";
import temperatureIcon from "./assets/temperature-icon.svg";

export const heroTitle =
  "Experience the Perfect Sleep with Our Premium Mattresses";
export const heroSubtitle =
  "Discover the ideal mattress for your ultimate comfort and restful sleep, all with us.";

export const services = [
  {
    title: "Free Shipping",
    subtitle: "No charge for your delivery",
    icon: shippingIcon,
  },
  {
    title: "Quick Payment",
    subtitle: "100% secure",
    icon: paymentIcon,
  },
  {
    title: "24/7 Support",
    subtitle: "Don't hesitate to contact us",
    icon: supportIcon,
  },
];

export const productsTitle = "Best Selling Products";
export const productsBtnText = "See Colection";

export const products = [
  {
    id: 1,
    title: "Atlas ",
    price: "$65.99",
    img: "/atlas.jpg",
    quote:
      "This Orthopaedic mattress category includes strong high-density rebonded foam.\n It also features super soft foam for perfect body support and natural spine alignment.",
    inner:
      " Bonnel coil spring, hard cotton felt High density PU foam, super soft foam& Rebonded foam",
    types: [
      {
        title: "Atlas Standard",
        img: "/atlas1.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "8",
              "10",
              "12",
              
            ],
          },
        ],
      },
      {
        title: "Atlas Pillow Top",
        img: "/atlas2.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "8",
              "10",
              "12",
              
            ],
          },
        ],
      },
      {
        title: "Atlas Euro Top",
        img: "/atlas3.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [

              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "8",
              "10",
              "12",
            ],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Heera ",
    price: "$75.00",
    img: "/heera.jpg",
    quote:
      "This Orthopaedic mattress category includes strong high-density rebonded foam.\n It also features super soft foam for perfect body support and natural spine alignment.",
    inner:
      " Bonnel coil spring, hard cotton felt High density PU foam, super soft foam& Rebonded foam",
    types: [
      {
        title: "Heera Standard",
        img: "/heera1.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "6",
              "8",
              "10",
              "12",
            ],
          },
        ],
      },
      {
        title: "Heera Pillow Top",
        img: "/heera2.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "6",
              "8",
              "10",
              "12",
            ],
          },
        ],
      },
      {
        title: "Heera Euro Top",
        img: "/heera3.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "6",
              "8",
              "10",
              "12",
            ],
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: "OrthoX ",
    price: "$88.50",
    img: "/ortho.jpg",
    quote:
      "This Orthopaedic mattress category includes strong high-density rebonded foam.\n It also features super soft foam for perfect body support and natural spine alignment.",
    inner:
      " Bonnel coil spring, hard cotton felt High density PU foam, super soft foam& Rebonded foam",
    types: [
      {
        title: "OrthoX Standard",
        img: "/ortho1.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "4",
              "5",
              "6",
              "8",
              "10",
            ],
          },
        ],
      },
      {
        title: "OrthoX pillow top",
        img: "/ortho2.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "4",
              "5",
              "6",
              "8",
              "10",
            ],
          },
        ],
      },
      {
        title: "OrthoX euro top",
        img: "/ortho3.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "4",
              "5",
              "6",
              "8",
              "10",
            ],
          },
        ],
      },
    ],
  },
  {
    id: 4,
    title: "Cresta ",
    price: "$88.50",
    img: "/cresta.jpg",
    quote:
      "This Orthopaedic mattress category includes strong high-density rebonded foam.\n It also features super soft foam for perfect body support and natural spine alignment.",
    inner:
      " Bonnel coil spring, hard cotton felt High density PU foam, super soft foam& Rebonded foam",
    types: [
      {
        title: "Cresta Standard",
        img: "/cresta1.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "8",
              "10",
              "12",
            ],
          },
        ],
      },
      {
        title: "Cresta Pillow Top",
        img: "/cresta2.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "8",
              "10",
              "12",
            ],
          },
        ],
      },
      {
        title: "Cresta Euro Top",
        img: "/cresta3.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "8",
              "10",
              "12",
            ],
          },
        ],
      },
    ],
  },
  {
    id: 5,
    title: "Mediline ",
    price: "$88.50",
    img: "/heera3.jpg",
    inner: "High density re- bonded. Foam &super soft foam",
    quote:
      "This Orthopaedic mattress category includes strong high-density rebonded foam.\n It also features super soft foam for perfect body support and natural spine alignment.",
    inner:
      " Bonnel coil spring, hard cotton felt High density PU foam, super soft foam& Rebonded foam",
    types: [
      {
        title: "Mediline Standard",
        img: "/cresta1.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "4",
              "5",
              "6",
              "8",
              "10",
            ],
          },
        ],
      },
      {
        title: "Mediline Pillow Top",
        img: "/cresta2.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "4",
              "5",
              "6",
              "8",
              "10",
            ],
          },
        ],
      },
      {
        title: "Mediline Euro Top",
        img: "/cresta3.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "4",
              "5",
              "6",
              "8",
              "10",
            ],
          },
        ],
      },
    ],
  },
  {
    id: 6,
    title: "Heera deluxe",
    price: "$88.50",
    img: "/cresta.jpg",
    quote:
    "This Orthopaedic mattress category includes strong high-density rebonded foam.\n It also features super soft foam for perfect body support and natural spine alignment.",
  inner:
    " Bonnel coil spring, hard cotton felt High density PU foam, super soft foam& Rebonded foam",
    types: [
      {
        title: "Memory Foam",
        img: "/cresta1.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "8",
              "10",
              "12",
            ],
          },
        ],
      },
      {
        title: "Heera Pillow Top",
        img: "/cresta2.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "8",
              "10",
              "12",
            ],
          },
        ],
      },
      {
        title: "Heera Euro Top",
        img: "/cresta3.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "8",
              "10",
              "12",
            ],
          },
        ],
      },
    ],
  },
  {
    id: 7,
    title: "Natural  latex",
    price: "$88.50",
    img: "/cresta.jpg",
    quote:
    "This Orthopaedic mattress category includes strong high-density rebonded foam.\n It also features super soft foam for perfect body support and natural spine alignment.",
  inner:
    " Bonnel coil spring, hard cotton felt High density PU foam, super soft foam& Rebonded foam",

    types: [
      {
        title: "Natural Standard",
        img: "/cresta1.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "4",
              "5",
              "6",
              "8",
              "10",
            ],
          },
        ],
      },
      {
        title: "Natural Pillow Top",
        img: "/cresta2.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "4",
              "5",
              "6",
              "8",
              "10",
            ],
          },
        ],
      },
      {
        title: "Natural Euro Top",
        img: "/cresta3.jpg",
        details: [
          {
            img: "/atlas1.jpg",
            sizes: [
              "72 x 36",
              "75 x 36",
              "78 x 36",
              "72 x 48",
              "75 x 48",
              "78 x 48",
              "72 x 60",
              "75 x 60",
              "78 x 60",
              "72 x 72",
              "75 x 72",
              "78 x 72",
              " ",
              " ",
              " ",
              "Inches (IN)",
              "4",
              "5",
              "6",
              "8",
              "10",
            ],
          },
        ],
      },
    ],
  },
];

export const newsletter = "Newsletter";

export const footerLinksColumnOne = [
  {
    title: "Support",
    links: ["About Us", "Careers"],
  },
];

export const footerLinksColumnTwo = [
  {
    title: "Our Menu",
    links: ["Best Product", "Categories"],
  },
  {
    title: "Address",
    links: [
      "Balan K Nair Road, Near Rajendra Hospital,Ashokapuram Building,Calicut 673001, Kerala ",
      "rayamattress@gmail.com",
    ],
  },
];
